/* =====================================================
   Project: Sales Performance Analysis
   Tool: MySQL
   Author: Gayathri Mandle
   Description: Product, Category, and Geographic Sales Analysis
===================================================== */

USE ecommerce_project;


/* ================================
   1. Product Revenue Analysis
================================ */

-- Revenue Generated by Each Product
SELECT 
    p.product_name,
    ROUND(SUM(oi.quantity * oi.price), 2) AS product_revenue
FROM order_items oi
JOIN products p 
ON oi.product_id = p.product_id
GROUP BY p.product_name
ORDER BY product_revenue DESC;


/* ================================
   2. Top Performing Products
================================ */

-- Top 10 Products by Revenue
SELECT 
    p.product_name,
    ROUND(SUM(oi.quantity * oi.price), 2) AS product_revenue
FROM order_items oi
JOIN products p 
ON oi.product_id = p.product_id
GROUP BY p.product_name
ORDER BY product_revenue DESC
LIMIT 10;


/* ================================
   3. Lowest Performing Products
================================ */

-- Bottom 10 Products by Revenue
SELECT 
    p.product_name,
    ROUND(SUM(oi.quantity * oi.price), 2) AS product_revenue
FROM order_items oi
JOIN products p 
ON oi.product_id = p.product_id
GROUP BY p.product_name
ORDER BY product_revenue ASC
LIMIT 10;


/* ================================
   4. Category Revenue Analysis
================================ */

-- Revenue by Product Category
SELECT 
    p.category,
    ROUND(SUM(oi.quantity * oi.price), 2) AS category_revenue
FROM order_items oi
JOIN products p 
ON oi.product_id = p.product_id
GROUP BY p.category
ORDER BY category_revenue DESC;


/* ================================
   5. Category Revenue Contribution
================================ */

-- Percentage Contribution by Category
SELECT 
    p.category,
    ROUND(SUM(oi.quantity * oi.price), 2) AS category_revenue,
    ROUND(
        SUM(oi.quantity * oi.price) /
        (SELECT SUM(quantity * price) FROM order_items) * 100,
        2
    ) AS revenue_percent
FROM order_items oi
JOIN products p 
ON oi.product_id = p.product_id
GROUP BY p.category
ORDER BY revenue_percent DESC;


/* ================================
   6. Geographic Revenue Analysis
================================ */

-- Revenue Generated by Each City
SELECT 
    c.city,
    ROUND(SUM(o.total_amount), 2) AS city_revenue
FROM orders o
JOIN customers c
ON o.customer_id = c.customer_id
GROUP BY c.city
ORDER BY city_revenue DESC;


/* ================================
   7. Top Performing Cities
================================ */

-- Top 10 Cities by Revenue
SELECT 
    c.city,
    ROUND(SUM(o.total_amount), 2) AS city_revenue
FROM orders o
JOIN customers c
ON o.customer_id = c.customer_id
GROUP BY c.city
ORDER BY city_revenue DESC
LIMIT 10;


/* ================================
   8. Product Revenue Ranking
================================ */

-- Ranking Products by Revenue
SELECT 
    p.product_name,
    ROUND(SUM(oi.quantity * oi.price), 2) AS product_revenue,
    RANK() OVER (ORDER BY SUM(oi.quantity * oi.price) DESC) AS revenue_rank
FROM order_items oi
JOIN products p 
ON oi.product_id = p.product_id
GROUP BY p.product_name;